services:
  combatrol:
    build: .
    container_name: combatrol_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - stack_net
    expose:
      - "8000"

networks:
  stack_net:
    external: true
    name: stack_net
